# This file was generated by GoReleaser. DO NOT EDIT.
cask "terminal-space-program" do
  version "0.16.1"

  on_macos do
    on_intel do
      sha256 "0314d0b7df2f989ffdc25f0bec7461ed6ea366102197e9d46d0de0af853bb5ee"
      url "https://github.com/jasonfen/terminal-space-program/releases/download/v#{version}/terminal-space-program-darwin-amd64.tar.gz"
    end
    on_arm do
      sha256 "63ea745d59518eaf3bc3d9caa4617175ed46a4674d96a39a8f68b4beeee34cd2"
      url "https://github.com/jasonfen/terminal-space-program/releases/download/v#{version}/terminal-space-program-darwin-arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "96277be6928d2992ebd7d26e020354fa9848673d57b1130e4b8b82988af0c3c3"
      url "https://github.com/jasonfen/terminal-space-program/releases/download/v#{version}/terminal-space-program-linux-amd64.tar.gz"
    end
    on_arm do
      sha256 "248d6252b272d7a170c789062e725683d40e24868cbe5ae7b5ac557e5cc114cf"
      url "https://github.com/jasonfen/terminal-space-program/releases/download/v#{version}/terminal-space-program-linux-arm64.tar.gz"
    end
  end

  name "terminal-space-program"
  desc "Terminal-native orbital-mechanics rocket simulator (KSP in your terminal)"
  homepage "https://github.com/jasonfen/terminal-space-program"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "terminal-space-program"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/terminal-space-program"]
    end
  end

  # No zap stanza required

end
