# This file was generated by GoReleaser. DO NOT EDIT.
cask "terminal-space-program" do
  version "0.44.2"

  on_macos do
    on_arm do
      sha256 "8351b9ef915b382a9d0ad0a4333099aa1d890cb71752e3d075d17a1b435ae0c6"
      url "https://github.com/jasonfen/terminal-space-program/releases/download/v#{version}/terminal-space-program-darwin-arm64.tar.gz"
    end
    on_intel do
      sha256 "64ffefb5cf1422ceb842a3bad0ef3c980eb7662d61f91b7fd1b16a0faebe2539"
      url "https://github.com/jasonfen/terminal-space-program/releases/download/v#{version}/terminal-space-program-darwin-amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "50c171eee8c91f93f388d4a0f051b2839a9855680196d0060b24d1f71b8eb84d"
      url "https://github.com/jasonfen/terminal-space-program/releases/download/v#{version}/terminal-space-program-linux-arm64.tar.gz"
    end
    on_intel do
      sha256 "90b636009d5ac190d993d62729722fbf774103468bd9c5b2b906a3079fe614d6"
      url "https://github.com/jasonfen/terminal-space-program/releases/download/v#{version}/terminal-space-program-linux-amd64.tar.gz"
    end
  end

  name "terminal-space-program"
  desc "Terminal-native orbital-mechanics rocket simulator (KSP in your terminal)"
  homepage "https://github.com/jasonfen/terminal-space-program"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "terminal-space-program"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/terminal-space-program"]
    end
  end

  # No zap stanza required
end
