# This file was generated by GoReleaser. DO NOT EDIT.
cask "terminal-space-program" do
  version "0.18.2"

  on_macos do
    on_intel do
      sha256 "b6eb0ece431599ec165c8e03f48dd8512abd9fccfd8bd67dbe2023468d90cf78"
      url "https://github.com/jasonfen/terminal-space-program/releases/download/v#{version}/terminal-space-program-darwin-amd64.tar.gz"
    end
    on_arm do
      sha256 "82d1a224d3963e556bfad09a504d8b69fb6676bc9995dedb92bbbbf31c3f2a43"
      url "https://github.com/jasonfen/terminal-space-program/releases/download/v#{version}/terminal-space-program-darwin-arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "6b01efdd62bf066bd768642c72faed61751a4c74b8d15b12139d9906ca798b34"
      url "https://github.com/jasonfen/terminal-space-program/releases/download/v#{version}/terminal-space-program-linux-amd64.tar.gz"
    end
    on_arm do
      sha256 "ac650e467ea2f1dd3c9a94d9ade5bd50e3dccac3b76c5280b7d8c0d33f7696ab"
      url "https://github.com/jasonfen/terminal-space-program/releases/download/v#{version}/terminal-space-program-linux-arm64.tar.gz"
    end
  end

  name "terminal-space-program"
  desc "Terminal-native orbital-mechanics rocket simulator (KSP in your terminal)"
  homepage "https://github.com/jasonfen/terminal-space-program"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "terminal-space-program"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/terminal-space-program"]
    end
  end

  # No zap stanza required

end
